CREATE TABLE SC_PERSON_SCHEDULES (
    SCHEDULE_ASSIGNMENT_ID  NUMBER          NOT NULL,
    PERSON_ID               NUMBER,
    PERSON_NUMBER           VARCHAR2(30),
    ASSIGNMENT_NUMBER       VARCHAR2(30),
    SCHEDULE_NAME           VARCHAR2(240),
    EFFECTIVE_FROM_DATE     DATE,
    EFFECTIVE_TO_DATE       DATE,
    START_DATE              DATE,
    END_DATE                DATE,
    PRIMARY_FLAG            VARCHAR2(1),
    CONSTRAINT SC_PERSON_SCHEDULES_PK PRIMARY KEY (SCHEDULE_ASSIGNMENT_ID)
);
