package com.ewsv3.ews.schedulers.service;

public class SchedulerSql {

    public static String getBISchedulers = """
            SELECT
                ( ( hour * 60 ) + minute ) minutes_delay
              FROM
                sc_scheduler_setup
             WHERE
                service_type = 'BI_REPORTS_EXECUTION'""";

    public static String getBiApis = """
            SELECT
                sii.integration_id,
                sii.name,
                sii.end_point
              FROM
                sc_inbound_integrations sii
             WHERE
                nvl(
                    enabled,
                    'N'
                ) = 'Y'
             AND sii.end_point is not null
             ORDER BY
                integration_id""";

    public static String cleanInterfaceTablesSql = """
             BEGIN
                 DELETE inb_departments;
                                    \s
                 DELETE inb_department_dff;
                                    \s
                 DELETE inb_jobs;
                                    \s
                 DELETE inb_job_families;
                                    \s
                 DELETE inb_workers;
                                    \s
                 DELETE inb_worker_citizenships;
                                    \s
                 DELETE inb_worker_emails;
                                    \s
                 DELETE inb_worker_names;
                                    \s
                 DELETE inb_worker_phones;
                                    \s
             END;
            \s""";

    public static String insertBusinessUnitSql = """
            INSERT INTO inb_business_units (
                business_unit_id,
                business_unit_name,
                status
            ) VALUES (
                ?,
                ?,
                ?
            )""";

    public static String insertDepartmentSql = """
            INSERT INTO inb_departments (
                department_id,
                department_name,
                effective_start_date,
                effective_end_date,
                classification_code,
                location_id,
                organization_code,
                status
            ) VALUES (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )""";

    public static String insertDepartmentDffSql = """
            INSERT INTO inb_department_dff (
                department_id,
                attribute_1,
                attribute_2,
                attribute_3,
                attribute_4,
                attribute_5
            ) VALUES (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )""";

    public static String insertJobSql = """
            INSERT INTO inb_jobs (
                job_id,
                job_code,
                job_family_id,
                active_status,
                full_part_time,
                job_function_code,
                manager_level,
                medical_checkup_required,
                standard_working_hours,
                standard_working_frequency,
                standard_annual_working_duration,
                annual_working_duration_units,
                regular_temporary,
                set_id,
                effective_start_date,
                effective_end_date,
                name,
                approval_authority,
                scheduling_group,
                grade_ladder_id,
                creation_date,
                last_update_date
            ) VALUES (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )""";

    public static String insertJobFamilySql = """
            INSERT INTO inb_job_families (
                job_family_id,
                effective_start_date,
                effective_end_date,
                job_family_name,
                job_family_code,
                action_reason_id,
                active_status,
                creation_date,
                last_update_date
            ) VALUES (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )""";

    public static String insertWorkerSql = """
            INSERT INTO inb_workers (
                person_id,
                person_number,
                correspondence_language,
                blood_type,
                date_of_birth,
                date_of_death,
                country_of_birth,
                region_of_birth,
                town_of_birth,
                applicant_number,
                creation_date,
                last_update_date,
                citizenships_Link,
                emails_Link,
                legislativeinfo_Link,
                names_Link,
                phones_Links,
                religions_Links,
                workrelationships_Link,
                workersdff_Link
            ) VALUES (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )""";

    public static String getAllWorkers = """
            SELECT
                person_id,
                person_number,
                correspondence_language,
                blood_type,
                date_of_birth,
                date_of_death,
                country_of_birth,
                region_of_birth,
                town_of_birth,
                applicant_number,
                creation_date,
                null created_By,
                last_update_date,
                null last_Updated_By,
                names_link,
                workersdff_link,
                legislativeinfo_link,
                citizenships_link,
                religions_links,
                workrelationships_link,
                emails_link,
                phones_links,
                null links
              FROM
                inb_workers""";

    public static String insertWorkerCitizenshipsSql = """
            INSERT INTO inb_worker_citizenships (
                person_id,
                citizenship_id,
                citizenship,
                from_date,
                to_date,
                citizenship_status,
                creation_date,
                last_update_date
            ) VALUES (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )""";

    public static String insertWorkerEmailsSql = """
            INSERT INTO inb_worker_emails (
                person_id,
                email_address_id,
                email_type,
                email_address,
                from_date,
                to_date,
                primary_flag,
                creation_date,
                last_update_date
            ) VALUES (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )""";
    public static String insertWorkerNamesSql = """
            INSERT INTO inb_worker_names (
                person_id,
                person_name_id,
                effective_start_date,
                effective_end_date,
                legislation_code,
                last_name,
                first_name,
                title,
                pre_name_adjunct,
                suffix,
                middle_names,
                honors,
                known_as,
                previous_last_name,
                display_name,
                order_name,
                list_name,
                full_name,
                military_rank,
                namelanguage,
                name_information1,
                name_information2,
                name_information3,
                name_information4,
                name_information5,
                name_information6,
                name_information7,
                name_information8,
                name_information9,
                name_information10,
                name_information11,
                name_information12,
                name_information13,
                name_information14,
                name_information15,
                name_information16,
                name_information17,
                name_information18,
                name_information19,
                name_information20,
                name_information21,
                name_information22,
                name_information23,
                name_information24,
                name_information25,
                name_information26,
                name_information27,
                name_information28,
                name_information29,
                name_information30,
                creation_date,
                last_update_date,
                local_person_name_id,
                local_effective_start_date,
                local_effective_end_date,
                locallegislation_code,
                local_last_name,
                local_first_name,
                local_title,
                local_pre_name_adjunct,
                local_suffix,
                local_middle_names,
                local_honors,
                local_knownas,
                local_previous_last_name,
                local_display_name,
                local_order_name,
                local_list_name,
                local_full_name,
                local_military_rank,
                local_name_language,
                local_name_information1,
                local_name_information2,
                local_name_information3,
                local_name_information4,
                local_name_information5,
                local_name_information6,
                local_name_information7,
                local_name_information8,
                local_name_information9,
                local_name_information10,
                local_name_information11,
                local_name_information12,
                local_name_information13,
                local_name_information14,
                local_name_information15,
                local_name_information16,
                local_name_information17,
                local_name_information18,
                local_name_information19,
                local_name_information20,
                local_name_information21,
                local_name_information22,
                local_name_information23,
                local_name_information24,
                local_name_information25,
                local_name_information26,
                local_name_information27,
                local_name_information28,
                local_name_information29,
                local_name_information30,
                local_creationdate,
                local_lastupdatedate
            ) VALUES (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )""";

    // static String insertWorkerNamesSql = """
    // INSERT INTO inb_worker_names (
    // person_id,
    // person_name_id,
    // effective_start_date,
    // effective_end_date,
    // legislation_code,
    // last_name,
    // first_name,
    // title,
    // pre_name_adjunct,
    // suffix,
    // middle_names,
    // honors,
    // known_as,
    // previous_last_name,
    // display_name,
    // order_name,
    // list_name,
    // full_name,
    // military_rank,
    // namelanguage,
    // name_information1,
    // name_information2,
    // name_information3,
    // name_information4,
    // name_information5,
    // name_information6,
    // name_information7,
    // name_information8,
    // name_information9,
    // name_information10,
    // name_information11,
    // name_information12,
    // name_information13,
    // name_information14,
    // name_information15,
    // name_information16,
    // name_information17,
    // name_information18,
    // name_information19,
    // name_information20,
    // name_information21,
    // name_information22,
    // name_information23,
    // name_information24,
    // name_information25,
    // name_information26,
    // name_information27,
    // name_information28,
    // name_information29,
    // name_information30,
    // creation_date,
    // last_update_date,
    // local_person_name_id,
    // local_effective_start_date,
    // local_effective_end_date,
    // locallegislation_code,
    // local_last_name,
    // local_first_name,
    // local_title,
    // local_pre_name_adjunct,
    // local_suffix,
    // local_middle_names,
    // local_honors,
    // local_knownas,
    // local_previous_last_name,
    // local_display_name,
    // local_order_name,
    // local_list_name,
    // local_full_name,
    // local_military_rank,
    // local_name_language,
    // local_name_information1,
    // local_name_information2,
    // local_name_information3,
    // local_name_information4,
    // local_name_information5,
    // local_name_information6,
    // local_name_information7,
    // local_name_information8,
    // local_name_information9,
    // local_name_information10,
    // local_name_information11,
    // local_name_information12,
    // local_name_information13,
    // local_name_information14,
    // local_name_information15,
    // local_name_information16,
    // local_name_information17,
    // local_name_information18,
    // local_name_information19,
    // local_name_information20,
    // local_name_information21,
    // local_name_information22,
    // local_name_information23,
    // local_name_information24,
    // local_name_information25,
    // local_name_information26,
    // local_name_information27,
    // local_name_information28,
    // local_name_information29,
    // local_name_information30,
    // local_creationdate,
    // local_lastupdatedate
    // ) VALUES (
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?,
    // ?
    // )""";

    public static String insertWorkerPhonesSql = """
            INSERT INTO inb_worker_phones (
                person_id,
                phone_id,
                phone_type,
                legislation_code,
                country_code_number,
                area_code,
                phone_number,
                extension,
                from_date,
                to_date,
                validity,
                creation_date,
                last_update_date,
                primary_flag
            ) VALUES (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )""";
}
