package com.ewsv3.ews.schedulers.dto.fusionDto.worker.assignments;

import com.ewsv3.ews.schedulers.dto.fusionDto.commons.LinksObject;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;

public record FusionAssignments(
        @JsonIgnore long personId,
        @JsonProperty("AssignmentId") Long assignmentId,
        @JsonProperty("AssignmentNumber") String assignmentNumber,
        @JsonProperty("AssignmentName") String assignmentName,
        @JsonProperty("ActionCode") String actionCode,
        @JsonProperty("ReasonCode") String reasonCode,
        @JsonProperty("EffectiveStartDate") LocalDate effectiveStartDate,
        @JsonProperty("EffectiveEndDate") LocalDate effectiveEndDate,
        @JsonProperty("EffectiveSequence") Long effectiveSequence,
        @JsonProperty("EffectiveLatestChange") String effectiveLatestChange,
        @JsonProperty("BusinessUnitId") Long businessUnitId,
        @JsonProperty("BusinessUnitName") String businessUnitName,
        @JsonProperty("AssignmentType") String assignmentType,
        @JsonProperty("AssignmentStatusTypeId") Long assignmentStatusTypeId,
        @JsonProperty("AssignmentStatusTypeCode") String assignmentStatusTypeCode,
        @JsonProperty("AssignmentStatusType") String assignmentStatusType,
        @JsonProperty("SystemPersonType") String systemPersonType,
        @JsonProperty("UserPersonTypeId") Long userPersonTypeId,
        @JsonProperty("UserPersonType") String userPersonType,
        @JsonProperty("ProposedUserPersonTypeId") Long proposedUserPersonTypeId,
        @JsonProperty("ProposedUserPersonType") String proposedUserPersonType,
        @JsonProperty("ProjectedStartDate") LocalDate projectedStartDate,
        @JsonProperty("ProjectedEndDate") LocalDate projectedEndDate,
        @JsonProperty("PrimaryFlag") String primaryFlag,
        @JsonProperty("PrimaryAssignmentFlag") String primaryAssignmentFlag,
        @JsonProperty("PositionId") Long positionId,
        @JsonProperty("PositionCode") String positionCode,
        @JsonProperty("SynchronizeFromPositionFlag") String synchronizeFromPositionFlag,
        @JsonProperty("JobId") Long jobId,
        @JsonProperty("JobCode") String jobCode,
        @JsonProperty("GradeId") Long gradeId,
        @JsonProperty("GradeCode") String gradeCode,
        @JsonProperty("GradeLadderId") Long gradeLadderId,
        @JsonProperty("GradeLadderName") String gradeLadderName,
        @JsonProperty("GradeStepEligibilityFlag") String gradeStepEligibilityFlag,
        @JsonProperty("GradeCeilingStepId") Long gradeCeilingStepId,
        @JsonProperty("GradeCeilingStep") String gradeCeilingStep,
        @JsonProperty("DepartmentId") Long departmentId,
        @JsonProperty("DepartmentName") String departmentName,
        @JsonProperty("ReportingEstablishmentId") Long reportingEstablishmentId,
        @JsonProperty("ReportingEstablishmentName") String reportingEstablishmentName,
        @JsonProperty("LocationId") Long locationId,
        @JsonProperty("LocationCode") String locationCode,
        @JsonProperty("WorkAtHomeFlag") String workAtHomeFlag,
        @JsonProperty("AssignmentCategory") String assignmentCategory,
        @JsonProperty("WorkerCategory") String workerCategory,
        @JsonProperty("PermanentTemporary") String permanentTemporary,
        @JsonProperty("FullPartTime") String fullParttime,
        @JsonProperty("ManagerFlag") String managerFlag,
        @JsonProperty("HourlySalariedCode") String hourlySalariedCode,
        @JsonProperty("NormalHours") Long normalHours,
        @JsonProperty("Frequency") String frequency,
        @JsonProperty("StartTime") String startTime,
        @JsonProperty("EndTime") String endTime,
        @JsonProperty("SeniorityBasis") String seniorityBasis,
        @JsonProperty("ProbationPeriod") Long probationPeriod,
        @JsonProperty("ProbationPeriodUnit") String probationPeriodUnit,
        @JsonProperty("ProbationEndDate") LocalDate probationEndDate,
        @JsonProperty("NoticePeriod") Long noticePeriod,
        @JsonProperty("NoticePeriodUOM") String noticePeriodUom,
        @JsonProperty("WorkTaxAddressId") Long workTaxAddressId,
        @JsonProperty("ExpenseCheckSendToAddress") String expenseCheckSendToAddress,
        @JsonProperty("RetirementAge") Long retirementAge,
        @JsonProperty("RetirementDate") LocalDate retirementDate,
        @JsonProperty("LabourUnionMemberFlag") String labourUnionMemberFlag,
        @JsonProperty("UnionId") Long unionId,
        @JsonProperty("UnionName") String unionName,
        @JsonProperty("BargainingUnitCode") String bargainingUnitCode,
        @JsonProperty("CollectiveAgreementId") Long collectiveAgreementId,
        @JsonProperty("CollectiveAgreementName") String collectiveAgreementName,
        @JsonProperty("ContractId") Long contractId,
        @JsonProperty("ContractNumber") String contractNumber,
        @JsonProperty("InternalBuilding") String internalBuilding,
        @JsonProperty("InternalFloor") String internalFloor,
        @JsonProperty("InternalOfficeNumber") String internalOfficeNumber,
        @JsonProperty("InternalMailstop") String internalMailstop,
        @JsonProperty("DefaultExpenseAccount") String defaultExpenseAccount,
        @JsonProperty("PeopleGroup") String peopleGroup,
        @JsonProperty("StandardWorkingHours") Long standardWorkingHours,
        @JsonProperty("StandardFrequency") String standardFrequency,
        @JsonProperty("CreatedBy") String createdBy,
        @JsonProperty("CreationDate") OffsetDateTime creationDate,
        @JsonProperty("LastUpdatedBy") String lastUpdatedBy,
        @JsonProperty("LastUpdateDate") OffsetDateTime lastUpdateDate,
        @JsonProperty("links") List<LinksObject> links
) {
}
